export default {
  numeroFactura: 9999999998,
  nombreRazonSocial: 'Control Tributario',
  codigoPuntoVenta: 1,
  codigoTipoDocumentoIdentidad: 1,
  numeroDocumento: '99002',
  codigoCliente: '99002',
  codigoMetodoPago: 1,
  montoTotal: 1,
  codigoMoneda: 1,
  montoTotalMoneda: 1,
  usuario: 'integracion',
  emailCliente: '',
  telefonoCliente: '',
  montoTotalSujetoIva: 1,
  tipoCambio: 1,
  extras: {
    facturaTicket: '',
  },
  detalles: [
    {
      codigoProducto: '',
      codigoActividadSin: '',
      codigoProductoSin: 99999999,
      descripcion: '',
      unidadMedida: 57,
      precioUnitario: 1,
      subTotal: 1,
      cantidad: 1,
    },
  ],
}
